### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by frederikhors** [archetect/archetect#11]
Is this abandoned?

**Comment by jimmiebfulton** [comment]
Not at all.  I use it heavily at my current company to pump out a variety of applications and automation.  What interest did you have in it?  It's quite sophisticated in it's capabilities, with more on the horizon, but it's lacking in adequate documentation.

**Comment by jimmiebfulton** [comment]
If you have an idea for an archetype, I'd be happy to throw one together for you so you to get your started.  Simple to create them, but lots of capability if you need something sophisticated.

**Comment by frederikhors** [comment]
Thank you very much for the answer. It all sounds great. This is exactly what I have in mind for an upcoming project.

I will get back to you as soon as possible.

Thanks again.
